/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AppointmentsRequestBuilderNavigationMetadata, AppointmentsRequestBuilderRequestsMetadata, type AppointmentsRequestBuilder } from './appointments/index.js';
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index.js';
// @ts-ignore
import { PatientsRequestBuilderNavigationMetadata, PatientsRequestBuilderRequestsMetadata, type PatientsRequestBuilder } from './patients/index.js';
// @ts-ignore
import { ServicesRequestBuilderNavigationMetadata, ServicesRequestBuilderRequestsMetadata, type ServicesRequestBuilder } from './services/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata, UsersRequestBuilderRequestsMetadata } from './users/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The appointments property
     */
    get appointments(): AppointmentsRequestBuilder;
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The patients property
     */
    get patients(): PatientsRequestBuilder;
    /**
     * The services property
     */
    get services(): ServicesRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    appointments: {
        requestsMetadata: AppointmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AppointmentsRequestBuilderNavigationMetadata,
    },
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    patients: {
        requestsMetadata: PatientsRequestBuilderRequestsMetadata,
        navigationMetadata: PatientsRequestBuilderNavigationMetadata,
    },
    services: {
        requestsMetadata: ServicesRequestBuilderRequestsMetadata,
        navigationMetadata: ServicesRequestBuilderNavigationMetadata,
    },
    users: {
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
