/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAddServiceResponseFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, createListServicesResponseFromDiscriminatorValue, serializeAddServiceRequest, serializeAddServiceResponse, type AddServiceRequest, type AddServiceResponse, type HttpValidationProblemDetails, type ListServicesResponse } from '../../models/index.js';
// @ts-ignore
import { ServicesItemRequestBuilderRequestsMetadata, type ServicesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/services
 */
export interface ServicesRequestBuilder extends BaseRequestBuilder<ServicesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.services.item collection
     * @param id Unique identifier of the item
     * @returns {ServicesItemRequestBuilder}
     */
     byId(id: Guid) : ServicesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListServicesResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<ServicesRequestBuilderGetQueryParameters> | undefined) : Promise<ListServicesResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AddServiceResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 409 status code
     */
     post(body: AddServiceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AddServiceResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ServicesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddServiceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface ServicesRequestBuilderGetQueryParameters {
    name?: string;
    pageIndex?: number;
    pageSize?: number;
}
/**
 * Uri template for the request builder.
 */
export const ServicesRequestBuilderUriTemplate = "{+baseurl}/api/services{?name*,pageIndex*,pageSize*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ServicesRequestBuilderNavigationMetadata: Record<Exclude<keyof ServicesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ServicesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ServicesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ServicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createListServicesResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ServicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            409: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAddServiceResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddServiceRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
